# Generated by Django 5.0.6 on 2024-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_aboutus_contact_contactinfo_findflight_howtobook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
            ],
        ),
    ]
