# Generated by Django 5.0.6 on 2024-07-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_categorypanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howtobookstep',
            name='number',
        ),
    ]
