# Generated by Django 5.0.6 on 2024-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_howtobookstep_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='full_name',
        ),
    ]
