# Generated by Django 5.0.6 on 2024-07-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_reply_email_remove_reply_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='categorypanel',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact informations'},
        ),
        migrations.AlterModelOptions(
            name='findflight',
            options={'verbose_name_plural': 'Find Flight'},
        ),
        migrations.AlterModelOptions(
            name='howtobook',
            options={'verbose_name_plural': 'How to Book'},
        ),
        migrations.AlterModelOptions(
            name='howtobookstep',
            options={'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterModelOptions(
            name='our_team',
            options={'verbose_name_plural': 'Our team'},
        ),
        migrations.AlterModelOptions(
            name='provide',
            options={'verbose_name_plural': 'Provide'},
        ),
        migrations.AlterModelOptions(
            name='recentvisitingplaces',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Sing ups'},
        ),
    ]
